### PR TITLE
Prepare 0.7.0 release

### LINKED ISSUE #51: Future proof the parsing of challenge types
When testing this with pebble https://github.com/letsencrypt/pebble this library fails to parse some of the challenge types that it offers. It would be good to make this enum `#[non_exhaustive]` and perhaps have an option for parsing the list of challenges to either ignore unknown types, or alternatively we could add a new variant something like:

```rust
#[derive(Clone, Debug, Deserialize, Eq, PartialEq)]
#[allow(missing_docs)]
#[non_exhaustive] // It's likely more variants may be added in the future.
pub enum ChallengeType {
    #[serde(rename = "http-01")]
    Http01,
    #[serde(rename = "dns-01")]
    Dns01,
    #[serde(rename = "tls-alpn-01")]
    TlsAlpn01,
    Unknown(String),
}
```

### PR DESCRIPTION
**Pull request by djc**
* Followup from #56 to clean things up a bit
* Cleanup from #50 
* Restore ability to build `HttpClient` implementations without hyper (after #50)
* Incorporate #54 (fixes #51)

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -800,9 +800,9 @@ pub trait BytesBody {
 }
 
 mod crypto {
-    #[cfg(all(feature = "aws-lc-rs", not(feature = "ring")))]
+    #[cfg(all(feature = "aws-lc-rs", any(feature = "fips", not(feature = "ring"))))]
     pub(crate) use aws_lc_rs as ring_like;
-    #[cfg(feature = "ring")]
+    #[cfg(all(feature = "ring", not(feature = "fips")))]
```
Comment (valkum) [inline src/lib.rs]: I think this is worth some explanations in the README.
As I understand it:
If `ring` and `aws-lc-rs` are enabled: `ring` takes precedence unless `fips` is also enabled, in which case `aws-lc-rs` takes precedence.

**Review by valkum — APPROVED** [review]
Only a small recommendation. Looks good otherwise.

File: src/lib.rs (hunk 1 above)
Comment (djc) [reply src/lib.rs]: That's fair, added a commit for this.

**Review by valkum — APPROVED** [review]
